# Two services: backend API on 5000, frontend (nginx) on 80
services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    # build:
    #   context: ./client
    #   args:
    #     VITE_API_URL: http://3.26.242.54:5000/api

    depends_on:
      - backend
